version: '3'
services:
  app1:
    build: .
    environment:
      - APP_NAME=App1
    ports:
      - "3001:3000"
    networks:
      - app-network
  app2:
    build: .
    environment:
      - APP_NAME=App2
    ports:
      - "3002:3000"
    networks:
      - app-network
  app3:
    build: .
    environment:
      - APP_NAME=App3
    ports:
      - "3003:3000"
    networks:
      - app-network
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - app1
      - app2
      - app3
networks:
  app-network:
    driver: bridge